logging:
  level: INFO
  loggers:
    com.example: DEBUG

server:
  type: simple
  rootPath: /api/
  applicationContextPath: /

database:
  # url: jdbc:h2:mem:test
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/dropwizard
  user: root
  password: root 
  